### ISSUE TITLE
AutoUpdater failed

### ISSUE THREAD

**Issue by MaverickC2** [NullSoldier/conan-server-manager#10]
Patch came out tonight and this showed in the logs:

[serverthrall.ServerUpdater] Autoupdater running, currently known buildid is 1645541
[serverthrall.ServerUpdater] Failed to check for update: Command '['C:\\ConanServer\\conan-server-manager-master\\vendor\\steamcmd\\steamcmd.exe', '+login anonymous', '+app_info_update 1', '+app_info_print 443030', '+app_info_print 443030', '+quit']' returned non-zero exit status 5
[serverthrall.ServerUpdater] Failed to check for update: Command '['C:\\ConanServer\\conan-server-manager-master\\vendor\\steamcmd\\steamcmd.exe', '+login anonymous', '+app_info_update 1', '+app_info_print 443030', '+app_info_print 443030', '+quit']' returned non-zero exit status 5

**Comment by NullSoldier** [comment]
Are you running this on the same machine as your normal steam installation?
For more information?

**Comment by MaverickC2** [comment]
Negative. My server runs on a dedicated VM running Windows Server 2016.

**Comment by MaverickC2** [comment]
Just an update:

I updated the server manually then when I started the server using your utility it ran the auto update. I can paste the log in a bit.

**Comment by NullSoldier** [comment]
I have a fix available. There are two separate problems here.. I'll release v1.2 tonight and add another comment when you can download it.

**Updater isn't detecting new updates properly**

So for one I found out that even though Im telling SteamCMD to fetch new version information, it actually caches that information and doesn't give me new information. This is stored in the "appcache" directory inside vendor/steamcmd. I now delete that folder before EVERY steamcmd operation. I introduced that into commit here, https://github.com/NullSoldier/conan-server-manager/commit/f5dbb7287ec0a81a84f052d4fb9dc94938d5d627

**SteamCMD is crashing causing those return error code 5 errors**

**Comment by NullSoldier** [comment]
Here is the latest release with a fix. It contains three major changes that you can read in the release notes. One behavioral change is that the updater plugin now only runs every 15 minutes. You can change that inside of your config file. There is a new option for it under ServerUpdater.

https://github.com/NullSoldier/conan-server-manager/releases/tag/v1.2
