### ISSUE TITLE
UPTime tracker

### ISSUE THREAD

**Issue by gabrielbuzziv** [NullSoldier/conan-server-manager#3]
I need to wait the UPTIMETRACKER?
For some reason this is downloading slow

**Comment by NullSoldier** [comment]
The server is downloading slowly?

You can disable the uptimetracker in the config if you set "enabled=false"

**Comment by gabrielbuzziv** [comment]
after i launch the server, start this downloading http://i.imgur.com/AoYSXb3.png?1

**Comment by NullSoldier** [comment]
That's not a downloader. It's a plugin that records when the server is up, or down and reporting it to the console. You should turn it off for now until I can make it spam less.

 - Open serverthrall.config
 - Find [UptimeTracker]
 - Set enabled=false

**Comment by gabrielbuzziv** [comment]
Ok, but what about this not loaded modules? =x 

![errors]http://i.imgur.com/TDaPIsP.png?1

**Comment by NullSoldier** [comment]
Those are bugs in Conan Exiles. They don't affect the game. You can ignore them.

**Comment by gabrielbuzziv** [comment]
Ok, i found that i had configured wrong the raidmanager, put 24 but need to be 0 kkk, lets try again

**Comment by gabrielbuzziv** [comment]
Got server running successfully, but who i put in the server list now?

**Comment by NullSoldier** [comment]
If you have it running, it'll automatically show up in the server list if your firewall has those ports open. You might only be able to see it on your LAN server list if your firewall is not open.

Once it launches the server all the normal documentation applies for how to run your server.

**Comment by gabrielbuzziv** [comment]
I need to have the game in the server machine too?

**Comment by gabrielbuzziv** [comment]
Where i set the server name, i`m confuse :X

**Comment by NullSoldier** [comment]
Try reading this. Skip to **Step 3**.
