### ISSUE TITLE
Feature Request: PVP Manager

### ISSUE THREAD

**Issue by MaverickC2** [NullSoldier/conan-server-manager#9]
Same as your raid plugin except this allows for PVP specified hours. It would also be nice if these plugins allowed more control over time. For example, allowing PVP or raiding structures on Friday, Saturday, and Sunday 1700-0300.

**Comment by NullSoldier** [comment]
I'll add those features into the raid plugin as options tonight.

**Comment by MaverickC2** [comment]
Awesome! No rush, I will likely be throwing you a bunch of ideas.

**Comment by NullSoldier** [comment]
Is it okay if this option is tied to "Raid" mode? Or would you want it to be completely separate?

**Comment by MaverickC2** [comment]
As long as you can enable/disable destroying structures and pvp separately then yes it should all be part of the raid plugin.

**Comment by MaverickC2** [comment]
Any plans to continue work on this project?

**Comment by NullSoldier** [comment]
I'm at GDC all week so I won't continue work until Sunday, but absolutely.
I'll start I'll speed ahead after this week.

**Comment by MaverickC2** [comment]
Awesome! I was just checking in.

**Comment by MaverickC2** [comment]
Feature no longer needed, they integrated into the game.

**Comment by NullSoldier** [comment]
I saw, nice!

**Comment by NullSoldier** [comment]
Yeah I saw, nice.
